### ISSUE TITLE
Traffic Router not honoring offline.

### ISSUE THREAD

**Issue by jpappa200** [Comcast/traffic_control#1535] opened 2016-06-20 21:35 UTC
When setting an edge from reported to offline Traffic Router will continue to redirect hosts after a snapshot. Setting the host to admin_down will stop the redirects. Going from admin_down to offline will cause a small trickle of redirects about 200 per minute.

**Comment by dneuman64** [comment] 2016-06-20 21:41
To Reproduce:  
1. Set a server from REPORTED to OFFLINE
2. Snapshot CrConfig
3. Check PeerStates in TM, the value will now be "" instead of "false".

**Comment by dneuman64** [comment] 2016-06-20 21:41
We should also not let Traffic Router route to a server when it is in this state.

**Comment by elsloo** [comment] 2016-06-20 22:27
Because `OFFLINE` hosts drop out of the cr-config, we should check for hosts that drop out in general. For example, this could potentially happen when a host is set to `REPORTED` and then deleted from Traffic Ops. State-wise it would transition from `REPORTED` to "missing" from the cr-config, which in effect is the same as going from `REPORTED` to `OFFLINE`.

**Comment by dneuman64** [comment] 2016-06-23 16:48
I tried to reproduce in Traffic Router with both 1.5.x and master and could not.  There must have been something else that happened that caused this issue to happen.
There is still an issue in Traffic Monitor, so I will fix that.

**Comment by dneuman64** [comment] 2016-06-28 16:14
Closing this issue as I could not reproduce.

**Closed by dneuman64** 2016-06-28 16:14 UTC
Labels: bug, Traffic Monitor, Traffic Router
