### ISSUE TITLE
Traffic Ops Delivery Service change for Max DNS requests returns to 0

### ISSUE THREAD

**Issue by G4m30v3r** [Comcast/traffic_control#1156] opened 2016-03-14 18:37 UTC
Editing Max DNS requests changes it to default 0 on save.

**Comment by elsloo** [comment] 2016-03-17 17:31
@G4m30v3r I just tested this in master (what will become 1.5.0) and I cannot reproduce the issue.

**Comment by G4m30v3r** [comment] 2016-03-17 17:39
produced this consistently on 1.4.0.2426. Showed output to elsloo directly.

**Comment by elsloo** [comment] 2016-03-17 20:34
Confirmed that this affects 1.4.x and a fix needs to be applied; most likely a backport from a commit that has already been made to master.

**Comment by dneuman64** [comment] 2016-03-18 17:47
closed by #1182

**Closed** 2016-03-18 17:48 UTC
Labels: bug, Traffic Ops
