### ISSUE TITLE
ORT trafficserver versions do not match distributed versions

### ISSUE THREAD

**Issue by limited** [Comcast/traffic_control#161] opened 2015-05-21 20:55 UTC
The current traffic_ops/install/data/json/parameter.json file has a trafficserver version of "5.2.0-5807.d0a1296.el6.x86_64". Theres' actually 3 trafficserver versions listed in that file, but that is the latest. 

traffic-control-cdn.net references 5.2.0-5809.b3586fc.el6.x86_64 for the current 1.1.2 release.

**Comment by elsloo** [comment] 2015-05-21 21:05
Also add some documentation that explains how ORT works with the package parameters.

**Comment by knutsel** [comment] 2015-08-07 15:21
dupe of #372

**Closed by knutsel** 2015-08-07 15:21 UTC
Labels: bug, documentation, enhancement, Traffic Ops
