### ISSUE TITLE
Need GUI to include production DNS servers in Generate ISO.

### ISSUE THREAD

**Issue by petrocc** [Comcast/traffic_control#308] opened 2015-07-14 17:13 UTC
Part of generating the ISO is including at least one prodution nameserver. Currently GenISO.pm is  reading /etc/resolv.conf to get those, which works for us, but might not for others.

**Comment by knutsel** [comment] 2015-08-07 15:26
dupe of #78

**Closed by knutsel** 2015-08-07 15:26 UTC
Labels: enhancement, Traffic Ops
