### ISSUE TITLE
The hardware tab in Traffic Ops needs some lookin' at. 

### ISSUE THREAD

**Issue by petrocc** [Comcast/traffic_control#458] opened 2015-08-20 21:39 UTC
The hardware tab in Traffic Ops returns so much data that firefox thinks the javascript that generates the tables has timed out.

Sometimes twice before the table is rendered. 

There's so much data that I suspect it's current form is un-usable.

**Comment by dangogh** [comment] 2015-09-03 21:53
Is this a duplicate of #325?

**Comment by petrocc** [comment] 2015-09-09 17:31
Probably close enough to a duplicate that they can be merged.

**Comment by dewrich** [comment] 2016-05-10 19:12
Solved by Issue: #325

**Closed by dewrich** 2016-05-10 19:12 UTC
Labels: enhancement, Traffic Ops
