### ISSUE TITLE
Health Server Checks - MTU column problem

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#185] opened 2015-06-01 17:04 UTC
I'm filling up most of the tables (ILO, 10G, 10G6, FQDN). I tried to add the MTU which seems like the database is updated properly. Although I'm filling up the correct field (ak) with 1 and 0, it never shows up as green on the Traffic Ops UI.

Example of data coming back from the API
```
["662","mcdlcdedge05","EDGE_R730XD_520","REPORTED","1","1","1","0",null,null,null,"0",null,null,null,"1",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]]}
```

**Comment by smalenfant** [comment] 2015-06-01 20:56
The CHR stats prints 0 and -1.

**Comment by limited** [comment] 2015-06-01 21:03
Hi Steve-
  I ran into this same issue last week and likewise opened a bug for it: https://github.com/Comcast/traffic_control/issues/159

There are a few more details there. I explain what the problem is, but not I wasn’t able to locate the root cause

—Eric
On Jun 1, 2015, at 4:56 PM, smalenfant <notifications@github.com<mailto:notifications@github.com>> wrote:


The CHR stats prints 0 and -1.

**Comment by smalenfant** [comment] 2015-06-02 11:20
This is a duplicate then. Wonder why I didn't see that one, maybe because I
looked in the release note for 1.1.2 only and not the open issues.

**Comment by knutsel** [comment] 2015-06-27 15:53
dupe of #159

**Closed by knutsel** 2015-06-27 15:53 UTC
