### ISSUE TITLE
Health Server Checks fails to show status on new database

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#271] opened 2015-06-30 03:59 UTC
A popup says something about `id == dtserverstatus` (related to JQuery?).

Once you run at least a check (like 10G) the problem disappear. Although I reset all my values to "Null" and I couldn't reproduce.

**Comment by knutsel** [comment] 2015-06-30 12:36
dupe of https://github.com/Comcast/traffic_control/issues/121

**Closed by knutsel** 2015-06-30 12:36 UTC
Labels: bug, Traffic Ops
