### ISSUE TITLE
Ops: Failed to disassociate parent cachegroup from edge cachegroup

### ISSUE THREAD

**Issue by xiaodzha** [Comcast/traffic_control#1432] opened 2016-05-20 02:36 UTC
Reproduction Steps:
1. Add cache group "middle" from OPS, type=MID_LOC;
2.Add cache group "edge" from OPS, type=EDGE_LOC, Parent Cache Group = "middle"
3. Then tried to disassociate parent cache group from edge cache group. When choosing  'NO PARENT' from the 'parent cache group' drop list and save it. 'middle' appears again in  parent cache group
** (This issue also can be reproduced against secondary parent cachegroup)

**Comment by smalenfant** [comment] 2016-05-20 11:01
Similar/duplicate of #1308

**Closed** 2016-05-23 19:42 UTC
