### ISSUE TITLE
postinstall: r154 version of jquery.flot.axislabels not available anymore

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#1451] opened 2016-05-24 16:57 UTC
From postinstall of 1.5.1 :

`Got HTTP 404 response for 'https://gflot.googlecode.com/svn-history/r154/trunk/flot/jquery.flot.axislabels.js'`

**Comment by mitchell852** [comment] 2016-05-25 20:30
This is a duplicate of #1453 which has been fixed.

**Comment by dangogh** [comment] 2016-05-26 21:08
fixed by #1454

**Closed by dangogh** 2016-05-26 21:08 UTC
Labels: bug, Traffic Ops
